name: sets_frontend_flutter
description: Dart(Flutter) build of the SETS Frontend GUI for both Android&#x2F;iOS
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:                  #flutter SDK
    sdk: flutter
  grpc: '>=0.6.1'           #gRPC dependencies
  protobuf: ^0.10.4
  cupertino_icons: ^0.1.2   #iOS icons
  scoped_model: ^0.3.0
  font_awesome_flutter: ^8.2.0
  device_id: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true  #Android icons
  # To add assets to your application, add an assets section, like this:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # To add custom fonts to your application, add a fonts section here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Medium.otf
      - asset: assets/fonts/Montserrat-Light.otf
        weight: 100